### ISSUE TITLE
fluid bug

### ISSUE THREAD

**Issue by n00b7** [andrewphorn/ClassiCube-Client#320]
if you build any block accept a fluid to the max height and try to put a fluid on top the client will say
The Game Broke! [java.lang.ArrayIndexOutOfBoundsException: 4239567]

i used the debug in the launcher options and heres the error:
14:01:40 [SEVERE] Fatal error in main loop (onFrame)
java.lang.ArrayIndexOutOfBoundsException: 4239567
	at com.mojang.minecraft.level.Level.processTickList(Level.java:1088)
	at com.mojang.minecraft.level.Level.tick(Level.java:1054)
	at com.mojang.minecraft.Minecraft.tick(Minecraft.java:1748)
	at com.mojang.minecraft.Minecraft.onFrame(Minecraft.java:870)
	at com.mojang.minecraft.Minecraft.run(Minecraft.java:813)
	at java.lang.Thread.run(Unknown Source)
14:06:21 [SEVERE] Error while playing music.
de.jarnbjo.ogg.EndOfOggStreamException
	at de.jarnbjo.ogg.LogicalOggStreamImpl.getNextOggPacket(LogicalOggStreamImpl.java:128)
	at de.jarnbjo.vorbis.VorbisStream.getNextAudioPacket(VorbisStream.java:126)
	at de.jarnbjo.vorbis.VorbisStream.readPcm(VorbisStream.java:206)
	at com.mojang.minecraft.sound.MusicPlayThread.run(MusicPlayThread.java:42)

v0.13

**Comment by fragmer** [comment]
Thanks for a detailed report! We will take a look and fix this.

On Jul 13, 2015 12:07 PM, "n00b7" <notifications@github.com> wrote:
>
> if you build any block accept a fluid to the max height and try to put a
fluid on top the client will say
> The Game Broke! [java.lang.ArrayIndexOutOfBoundsException: 4239567]
>
> i used the debug in the launcher options and heres the error:
> 14:01:40 [SEVERE] Fatal error in main loop (onFrame)
> java.lang.ArrayIndexOutOfBoundsException: 4239567
> at com.mojang.minecraft.level.Level.processTickList(Level.java:1088)
> at com.mojang.minecraft.level.Level.tick(Level.java:1054)
> at com.mojang.minecraft.Minecraft.tick(Minecraft.java:1748)
> at com.mojang.minecraft.Minecraft.onFrame(Minecraft.java:870)
> at com.mojang.minecraft.Minecraft.run(Minecraft.java:813)
> at java.lang.Thread.run(Unknown Source)
> 14:06:21 [SEVERE] Error while playing music.
> de.jarnbjo.ogg.EndOfOggStreamException
> at
de.jarnbjo.ogg.LogicalOggStreamImpl.getNextOggPacket(LogicalOggStreamImpl.java:128)
> at
de.jarnbjo.vorbis.VorbisStream.getNextAudioPacket(VorbisStream.java:126)

**Comment by 123DMWM** [comment]
What badly written server are you getting this on?
