### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by crasyleg73** [andrewphorn/ClassiCube-Client#326]
It told me to report it on github. here is the log:
=== crash occurred ===
Time: 5/20/2017 9:22:05 PM
Running on: .NET 2.0.50727.8784, Windows - 6.2.9200.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Launcher.Web.ClassicubeSession.Login(String user, String password)
   at Launcher.Web.ClassicubeSession.LoginWorker(Object password)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by UnknownShadow200** [comment]
Why didn't you open it at https://github.com/UnknownShadow200/ClassicalSharp/issues

edit: were you signing in, pressing reload button, I need more details
